Plotting refactor
pandas-profiling/pandas-profiling pull request #589
Opened 2020-09-26 23:43 UTC by sbrugman

- Multiple plotting backends: matplotlib and altair
- IEEE Fraud Detection example
- Numeric: QQ-plots for normal and uniform distributions
- Numeric: negative count / percentage
- Lazy loading of external images
- Interactions: cat/cat and cat/num (heatmaps)

2020-11-12 09:33 UTC, MichaelCurrin requested changes

2020-11-12 09:33 UTC, MichaelCurrin commented on examples/bank_marketing_data/banking_data.py
> +        # html=dict(inline=False),
Should this be uncommented, otherwise can it be taken out?

2021-01-25 11:00 UTC, jamesmyatt commented on examples/census/census.py
> +    profile = ProfileReport(
This should be one line

2021-01-25 11:01 UTC, jamesmyatt commented on examples/titanic/titanic.py
> +    profile = ProfileReport(
Should this be one line?

2021-09-15 20:08 UTC, closed without merging